import turtle
turtle.title("triangle")
t = turtle.Turtle()
s = turtle.Screen()
t.speed(2)
s.bgcolor("black")
t.penup()
t.goto(-50,60)
t.pendown()
t.color("green")
t.begin_fill()
t.goto(100,100)
t.goto(100,-100)
t.end_fill()
t.color("black")
input('press enter to exit')